---
micronaut:
  application:
    name: insurance-management
---
kafka:
  producers:
    insurance-producer:
      retries: 5
    customer-producer:
      retries: 5
    consumers:
      insurance-consumer:
      customer-consumer:
  streams:
    insurance-all-stream:
      client.id: insurances-client
      application-id: micronaut-kafka-stream-insurances
      group.id: insurances-group-id
  bootstrap:
    servers: localhost:9092
---
graphql:
  enabled: true
  path: /graphql
  graphiql:
    enabled: true
    path: /graphiql