---
micronaut:
  application:
    name: insurance-management
---
kafka:
  producers:
    insurance-producer:
      retries: 5
    customer-producer:
      retries: 5
  consumers:
    sale-consumer:
      session:
        timeout:
          ms: 30000
  streams:
    insurance-all-stream:
      client.id: insurances-managemet-client
      application-id: micronaut-kafka-stream-insurances-management
      group.id: insurances-management-group-id
  bootstrap:
    servers: localhost:9092
---
graphql:
  enabled: true
  path: /graphql
  corsEnabled: true
  websocket:
    enabled: true
    path: /graphql
  graphiql:
    enabled: true
    path: /graphiql